[package]
name = "webpage"
description = "Small library to fetch info about a web page"
readme = "README.md"
keywords = ["webpage", "html", "opengraph"]
license = "MIT"
version = "0.1.1"
authors = ["Otto <otto@ot-to.nl>"]
repository = "https://github.com/orottier/webpage-rs"

[dependencies]
curl = "0.4.12"
html5ever = "0.22.3"
serde_json = "1.0"
